# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "zohoho"
  s.version = "0.2.2"
  s.authors = ["Ilya Andreyuk"]
  s.date = "2012-09-20"
  s.description = "Fork from KentonWhite zohoho api wrapper"
  s.email = "aimilandr@gmail.com"

  s.homepage = "http://github.com/IluhaAndr/zohoho"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Simple interface to zoho api"

end

